name: 'Release'

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up version variables
        run: |
          awk -F'=' '
            /^artifact_name=/ {print "PROJECT_ARTIFACT_NAME=" $2}
            /^minecraft_version=/ {print "MINECRAFT_VERSION=" $2}
            /^mod_name=/ {print "MOD_NAME=" $2}
            /^mod_version=/ {print "MOD_VERSION=" $2}
            /^mod_discord_icon=/ {print "MOD_DISCORD_ICON=" $2}
            /^mod_github=/ {print "MOD_GITHUB=" $2}
            /^curseforge_project=/ {print "CURSEFORGE_PROJECT=" $2}
            /^modrinth_project=/ {print "MODRINTH_PROJECT=" $2}
            /^modrinth_project_slug=/ {print "MODRINTH_PROJECT_SLUG=" $2}
          ' gradle.properties >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "GITHUB_RELEASE_TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "MOD_CHANGELOG=$(echo "${{ github.event.release.body }}" | sed -E '/^\s*$/d; s#Full Changelog: (https?://[^\ ]+)#\[Full Changelog\](\1)#g')" >> $GITHUB_ENV
      - name: Prepare Discord webhook JSON file
        run: |
          envsubst < .github/workflows/release_published.json > prepared_release_published.json
      - name: Print setup information
        run: |
          echo "Set up for ${{ env.PROJECT_ARTIFACT_NAME }} version ${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          echo "CurseForge project: ${{ env.CURSEFORGE_PROJECT }}"
          echo "Modrinth project: ${{ env.MODRINTH_PROJECT_SLUG }} (${{ env.MODRINTH_PROJECT }})"
          echo ""
          echo "Raw Discord webhook JSON:"
          cat prepared_release_published.json
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to ModMaven
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishMavenJavaPublicationToModmavenRepository
        env:
          MODMAVEN_USERNAME: ${{ secrets.MODMAVEN_USERNAME }}
          MODMAVEN_PASSWORD: ${{ secrets.MODMAVEN_PASSWORD }}
      - name: Upload to Curseforge
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          MOD_CHANGELOG: ${{ github.event.release.body }}
        run: ./gradlew curseforge
      - name: Upload to Modrinth
        env:
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          MOD_CHANGELOG: ${{ github.event.release.body }}
        run: ./gradlew modrinth
      - name: Post to Discord webhook
        run: |
          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data @prepared_release_published.json ${{ secrets.RELEASE_WEBHOOK_URL }}
