name: 'Test'

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: The changelog for the discord message to use
        required: true
        default: |
          - Testing lines\n
          - Testing another line!\n
          \n
          Full Changelog: https://github.com/Swedz/Extended-Industrialization/compare/1.5.1+1.21...1.5.2+1.21

jobs:
  load-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load gradle.properties into the environment
        run: |
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^#.* ]] && continue
            env_key=$(echo "$key" | tr '[:lower:]' '[:upper:]' | tr '.' '_')
            echo "${env_key}=${value}" >> env_vars
          done < gradle.properties
      - name: Load github variables into the environment
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> env_vars
          echo "GITHUB_RELEASE_TAG_NAME=${{ github.event.release.tag_name }}" >> env_vars
          echo "MOD_CHANGELOG=${{ github.event.release.body }}" >> env_vars
      - name: Generate additional variables into the environment
        run: |
          echo "MOD_CHANGELOG_TRIMMED=$(echo "$MOD_CHANGELOG" | sed -E '/^\s*$/d; s#Full Changelog: (https?://[^\ ]+)#\[Full Changelog\](\1)#g')" >> env_vars
          echo "EMBED_COLOR=$(if [ $RELEASE_TYPE == "release" ]; then echo 2336090; elif [ $RELEASE_TYPE == "beta" ]; then echo 15774258; else echo 15875907; fi)" >> env_vars
      - name: Save environment variables
        uses: actions/upload-artifact@v2
        with:
          name: env_vars
          path: env_vars

  build:
    runs-on: ubuntu-latest
    needs: load-env
    steps:
      - uses: actions/checkout@v2
      - name: Download environment variables
        uses: actions/download-artifact@v2
        with:
          name: env_vars
      - name: Set environment variables
        run: |
          cat env_vars >> $GITHUB_ENV
      - name: Print setup information
        run: |
          echo "Set up for ${{ env.ARTIFACT_NAME }} version ${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          echo "CurseForge project: ${{ env.CURSEFORGE_PROJECT }}"
          echo "Modrinth project: ${{ env.MODRINTH_PROJECT_SLUG }} (${{ env.MODRINTH_PROJECT }})"