name: 'Test'

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: The changelog for the discord message to use
        required: true
        default: |
          - Testing lines\n
          - Testing another line!\n
          \n
          Full Changelog: https://github.com/Swedz/Extended-Industrialization/compare/1.5.1+1.21...1.5.2+1.21

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read gradle.properties
        run: |
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^#.* ]] && continue
            env_key=$(echo "$key" | tr '[:lower:]' '[:upper:]' | tr '.' '_')
            echo "${env_key}=${value}" >> $GITHUB_ENV
          done < gradle.properties
      - name: Print setup information
        run: |
          echo "Set up for ${{ env.ARTIFACT_NAME }} version ${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          echo "CurseForge project: ${{ env.CURSEFORGE_PROJECT }}"
          echo "Modrinth project: ${{ env.MODRINTH_PROJECT_SLUG }} (${{ env.MODRINTH_PROJECT }})"
