name: 'Test'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up version variables
        run: |
          awk -F'=' '
            /^artifact_name=/ {print "PROJECT_ARTIFACT_NAME=" $2}
            /^minecraft_version=/ {print "MINECRAFT_VERSION=" $2}
            /^mod_name=/ {print "MOD_NAME=" $2}
            /^mod_version=/ {print "MOD_VERSION=" $2}
            /^mod_discord_icon=/ {print "MOD_DISCORD_ICON=" $2}
            /^mod_github=/ {print "MOD_GITHUB=" $2}
            /^curseforge_project=/ {print "CURSEFORGE_PROJECT=" $2}
            /^modrinth_project=/ {print "MODRINTH_PROJECT=" $2}
            /^modrinth_project_slug=/ {print "MODRINTH_PROJECT_SLUG=" $2}
          ' gradle.properties >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "GITHUB_RELEASE_TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          MOD_CHANGELOG=$(echo "${{ github.event.release.body }}" | sed -E '/^\s*$/d; s#Full Changelog: (https?://[^\ ]+)#\[Full Changelog\](\1)#g')
          echo "MOD_CHANGELOG=$MOD_CHANGELOG" >> $GITHUB_ENV
      - name: Prepare Discord webhook JSON file
        run: |
          envsubst < .github/workflows/release_published.json > prepared_release_published.json
      - name: Print setup information
        run: |
          echo "Set up for ${{ env.PROJECT_ARTIFACT_NAME }} version ${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          echo "CurseForge project: ${{ env.CURSEFORGE_PROJECT }}"
          echo "Modrinth project: ${{ env.MODRINTH_PROJECT_SLUG }} (${{ env.MODRINTH_PROJECT }})"
          echo ""
          echo "Raw Discord webhook JSON:"
          cat prepared_release_published.json
      - name: Post to Discord webhook
        run: |
          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data @prepared_release_published.json ${{ secrets.RELEASE_WEBHOOK_URL }}
