name: 'Test'

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: The changelog for the discord message to use
        required: true
        default: |
          - Testing lines\n
          - Testing another line!\n
          \n
          Full Changelog: https://github.com/Swedz/Extended-Industrialization/compare/1.5.1+1.21...1.5.2+1.21

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read Gradle Properties
        id: gradle-properties
        uses: amadornes/parse-properties-action@v1.0
        with:
          file: gradle.properties
      - name: Set environment variables
        run: |
          for output in $(echo "${{ steps.gradle-properties.outputs }}"); do
            key=$(echo $output | awk -F '=' '{print $1}' | tr '[:lower:]' '[:upper:]')
            value=$(echo $output | awk -F '=' '{print $2}')
            echo "${key}=${value}" >> $GITHUB_ENV
          done
      - name: Print setup information
        run: |
          echo "Set up for ${{ env.ARTIFACT_NAME }} version ${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          echo "CurseForge project: ${{ env.CURSEFORGE_PROJECT }}"
          echo "Modrinth project: ${{ env.MODRINTH_PROJECT_SLUG }} (${{ env.MODRINTH_PROJECT }})"
